In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("diabetes.csv")          ###Load the dataset

In [3]:
df.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
df.isnull().sum()                                                   ##No missing values

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [5]:
X=df.drop("Outcome",axis=1).values                                  #Independent feature
y=df["Outcome"].values                                              #Dependent Feature

In [6]:
from sklearn.model_selection import train_test_split                                                  ### Train Test split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [7]:
X_train.shape

(614, 8)

In [8]:
X_test.shape

(154, 8)

In [9]:
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [45]:
from sklearn.ensemble import RandomForestClassifier

In [46]:
rf=RandomForestClassifier()

In [47]:
rf.fit(X_train,y_train)

RandomForestClassifier()

In [48]:
y_pred=rf.predict(X_test)

In [49]:
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [16]:
## accuracy score
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report     ##For this classification problem find out the accuracy,confusion matrix and classification report

In [50]:
accuracy_score(y_pred,y_test)

0.7987012987012987

In [51]:
confusion_matrix(y_pred,y_test)

array([[92, 16],
       [15, 31]], dtype=int64)

In [52]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.86      0.85      0.86       108\n           1       0.66      0.67      0.67        46\n\n    accuracy                           0.80       154\n   macro avg       0.76      0.76      0.76       154\nweighted avg       0.80      0.80      0.80       154\n'

In [10]:
from sklearn.ensemble import GradientBoostingClassifier

In [11]:
gb=GradientBoostingClassifier()

In [12]:
gb.fit(X_train,y_train)

GradientBoostingClassifier()

In [13]:
y_pred1=gb.predict(X_test)

In [14]:
y_pred1

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [17]:
accuracy_score(y_pred1,y_test)

0.8116883116883117

In [18]:
confusion_matrix(y_pred1,y_test)

array([[93, 15],
       [14, 32]], dtype=int64)

In [19]:
classification_report(y_pred1,y_test)

'              precision    recall  f1-score   support\n\n           0       0.87      0.86      0.87       108\n           1       0.68      0.70      0.69        46\n\n    accuracy                           0.81       154\n   macro avg       0.78      0.78      0.78       154\nweighted avg       0.81      0.81      0.81       154\n'

In [20]:
from sklearn.svm import SVC

In [21]:
svc=SVC()

In [22]:
svc.fit(X_train,y_train)

SVC()

In [23]:
y_pred2=svc.predict(X_test)

In [24]:
accuracy_score(y_pred2,y_test)

0.7922077922077922

In [25]:
confusion_matrix(y_pred2,y_test)

array([[98, 23],
       [ 9, 24]], dtype=int64)

In [26]:
classification_report(y_pred2,y_test)

'              precision    recall  f1-score   support\n\n           0       0.92      0.81      0.86       121\n           1       0.51      0.73      0.60        33\n\n    accuracy                           0.79       154\n   macro avg       0.71      0.77      0.73       154\nweighted avg       0.83      0.79      0.80       154\n'

In [27]:
from sklearn.ensemble import AdaBoostClassifier

In [28]:
Ad=AdaBoostClassifier()

In [29]:
Ad.fit(X_train,y_train)

AdaBoostClassifier()

In [30]:
y_pred3=Ad.predict(X_test)

In [31]:
accuracy_score(y_pred3,y_test)

0.7792207792207793

In [33]:
confusion_matrix(y_pred3,y_test)

array([[89, 16],
       [18, 31]], dtype=int64)

In [34]:
classification_report(y_pred3,y_test)

'              precision    recall  f1-score   support\n\n           0       0.83      0.85      0.84       105\n           1       0.66      0.63      0.65        49\n\n    accuracy                           0.78       154\n   macro avg       0.75      0.74      0.74       154\nweighted avg       0.78      0.78      0.78       154\n'

### Hyperparameter tunning of different different models using GridSearchCV

 ## GridSearchCV in RandomForest



In [53]:
##Numberof trees in RandomForset

n_estimators=[20,60,100,120]

##Number of features to consider at every split

max_features=[0.2,0.6,1.0]


##Maximum numbers of levels in a tree

max_depth=[2,8,None]

##Number of samples

max_samples=[0.5,0.75,1.0]

In [54]:
params={"n_estimators" : n_estimators,
             "max_features" : max_features,
             "max_depth" : max_depth,
             "max_samples" : max_samples
            }

In [68]:
rf=RandomForestClassifier()

In [55]:
from sklearn.model_selection import GridSearchCV
rf_grid=GridSearchCV(estimator=rf,param_grid=params,cv=5,verbose=2,n_jobs=-1)      ##Verbose is used to see all the outputs/description

In [56]:
rf_grid.fit(X_train,y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [2, 8, None],
                         'max_features': [0.2, 0.6, 1.0],
                         'max_samples': [0.5, 0.75, 1.0],
                         'n_estimators': [20, 60, 100, 120]},
             verbose=2)

In [57]:
rf_grid.best_params_

{'max_depth': 2, 'max_features': 0.6, 'max_samples': 0.5, 'n_estimators': 60}

In [58]:
rf_grid.best_score_

0.7622417699586832

In [59]:
y_pred=rf_grid.predict(X_test)

In [60]:
y_pred

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
      dtype=int64)

In [61]:
accuracy_score(y_pred,y_test)

0.7922077922077922

In [62]:
confusion_matrix(y_pred,y_test)

array([[98, 23],
       [ 9, 24]], dtype=int64)

In [63]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.92      0.81      0.86       121\n           1       0.51      0.73      0.60        33\n\n    accuracy                           0.79       154\n   macro avg       0.71      0.77      0.73       154\nweighted avg       0.83      0.79      0.80       154\n'

## RandomizedSearchCV

In [64]:
##Numberof trees in RandomForset

n_estimators=[20,60,100,120]

##Number of features to consider at every split

max_features=[0.2,0.6,1.0]


##Maximum numbers of levels in a tree

max_depth=[2,8,None]

##Number of samples

max_samples=[0.5,0.75,1.0]

##Bootstrap Samples

bootstrap=[True,False]

##Minimum number of samples required to split a node

min_samples_split=[2,5]

##Minimum number of samples required at each leaf node

min_samples_leaf=[1,2]

In [65]:
params={"n_estimators" : n_estimators,
             "max_features" : max_features,
             "max_depth" : max_depth,
             "max_samples" : max_samples,
             "bootstrap" : bootstrap,
             "min_samples_split" : min_samples_split,
             "min_samples_leaf" : min_samples_leaf
            }

In [66]:
from sklearn.model_selection import RandomizedSearchCV
rf_random=RandomizedSearchCV(estimator=rf,param_distributions=params,cv=5,verbose=2,n_jobs=-1)      ##Verbose is used to see all the outputs/description

In [67]:
rf_random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


C:\Users\nikit\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
35 fits failed out of a total of 50.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
35 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\nikit\anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\nikit\anaconda3\lib\site-packages\sklearn\ensemble\_forest.py", line 397, in fit
    raise ValueError(
ValueError: `max_sample` cannot be set if `bootstrap=False`. Either switch to `bootstrap=True` or set `max_sample=None`.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users

RandomizedSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
                   param_distributions={'bootstrap': [True, False],
                                        'max_depth': [2, 8, None],
                                        'max_features': [0.2, 0.6, 1.0],
                                        'max_samples': [0.5, 0.75, 1.0],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [20, 60, 100, 120]},
                   verbose=2)

In [68]:
rf_random.best_params_

{'n_estimators': 60,
 'min_samples_split': 5,
 'min_samples_leaf': 1,
 'max_samples': 0.5,
 'max_features': 1.0,
 'max_depth': 2,
 'bootstrap': True}

In [69]:
rf_random.best_score_

0.7491803278688525

In [70]:
y_pred=rf_random.predict(X_test)

In [71]:
accuracy_score(y_pred,y_test)

0.7727272727272727

In [72]:
confusion_matrix(y_pred,y_test)

array([[96, 24],
       [11, 23]], dtype=int64)

In [73]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.90      0.80      0.85       120\n           1       0.49      0.68      0.57        34\n\n    accuracy                           0.77       154\n   macro avg       0.69      0.74      0.71       154\nweighted avg       0.81      0.77      0.78       154\n'

## Hyperparameter tunning of Gradientboosting by RandomizedSearchCV

In [35]:
##Numberof trees in GradientBoosting

n_estimators=[20,60,100,120]

##Number of features to consider at every split

max_features=[0.2,0.6,1.0]


##Maximum numbers of levels in a tree

max_depth=[2,8,None]


##Minimum number of samples required to split a node

min_samples_split=[2,5]

##Minimum number of samples required at each leaf node

min_samples_leaf=[1,2]

## learning rate

learning_rate=[0.05,0.1,0.2,0.3,1.0]

##random_state

random_state=[0,10,42,100]

##losses that we will take

loss=['log_loss', 'deviance', 'exponential']

In [36]:
params={"n_estimators" : n_estimators,
             "max_features" : max_features,
             "max_depth" : max_depth,
             "min_samples_split" : min_samples_split,
             "min_samples_leaf" : min_samples_leaf,
             "learning_rate" : learning_rate,
             "random_state" : random_state,
             "loss" : loss
            }

In [37]:
from sklearn.model_selection import RandomizedSearchCV
gb_random=RandomizedSearchCV(estimator=gb,param_distributions=params,cv=5,verbose=2,n_jobs=-1)      ##Verbose is used to see all the outputs/description

In [38]:
gb_random.fit(X_train,y_train)

Fitting 5 folds for each of 10 candidates, totalling 50 fits


C:\Users\nikit\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:280: FutureWarning: The loss parameter name 'deviance' was deprecated in v1.1 and will be removed in version 1.3. Use the new parameter name 'log_loss' which is equivalent.
  warnings.warn(


RandomizedSearchCV(cv=5, estimator=GradientBoostingClassifier(), n_jobs=-1,
                   param_distributions={'learning_rate': [0.05, 0.1, 0.2, 0.3,
                                                          1.0],
                                        'loss': ['log_loss', 'deviance',
                                                 'exponential'],
                                        'max_depth': [2, 8, None],
                                        'max_features': [0.2, 0.6, 1.0],
                                        'min_samples_leaf': [1, 2],
                                        'min_samples_split': [2, 5],
                                        'n_estimators': [20, 60, 100, 120],
                                        'random_state': [0, 10, 42, 100]},
                   verbose=2)

In [40]:
gb_random.best_params_

{'random_state': 42,
 'n_estimators': 100,
 'min_samples_split': 2,
 'min_samples_leaf': 2,
 'max_features': 0.2,
 'max_depth': 8,
 'loss': 'deviance',
 'learning_rate': 0.1}

In [41]:
gb_random.best_score_

0.7524990003998401

In [42]:
y_pred=gb_random.predict(X_test)

In [43]:
accuracy_score(y_pred,y_test)

0.7857142857142857

In [44]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.82      0.86      0.84       102\n           1       0.70      0.63      0.67        52\n\n    accuracy                           0.79       154\n   macro avg       0.76      0.75      0.75       154\nweighted avg       0.78      0.79      0.78       154\n'